### ISSUE TITLE
syntax error in analyze_udos.inc

### ISSUE THREAD

**Issue by sensestage** [Oeyvind/featexmod#23]
I am getting the syntax error below when opening analyzer.csd in cabbage...

```
error: syntax error, unexpected T_IDENT  (token "kFFT") from file analyze_udos.inc (2)
 from file /home/nescivi/git/projects/CrossAdaptive/featexmod/analyzer.csd (1)
 line 325:
>>>kFFT <<<
Parsing failed due to invalid input!
Stopping on parser failure
cannot compile orchestra
```

**Comment by Oeyvind** [comment]
Thanks for the report.
Could you try running it in the terminal, to see if there is some more detail to the error?
cd to the directory and run
csound analyzer.csd

If it runs without error, you will have to terminate it with Ctrl+C.
Please post the terminal output (successful or not).

If it fails in the terminal too, please try to run:
csound -z
which lists all available opcodes, and check if rfft is in the list.

**Comment by Oeyvind** [comment]
... also please check Csound version number, printed (close to the top, 3rd or 4th line of the console output) every time you run csound in the terminal.

**Comment by sensestage** [comment]
rfft is in the list of opcodes.
I installed the CSound from the repositories of Ubuntu Xenial (16.04).

```
nescivi@exometheus:~/git/projects/CrossAdaptive/featexmod$ csound analyzer.csd 
virtual_keyboard real time MIDI plugin for Csound
0dBFS level = 32768.0
Csound version 6.04 (double samples) 2016-02-21
libsndfile-1.0.25
UnifiedCSD:  analyzer.csd
STARTING FILE
Creating options
Creating orchestra
Creating score
rtaudio: ALSA module enabled
defining argument _PUBLISH__N as...#0#
defining argument _PUBLISH__N as...#1#
defining argument _PUBLISH__N as...#2#

error: syntax error, unexpected T_IDENT  (token "kFFT") from file analyze_udos.inc (2)
 from file analyzer.csd (1)
 line 325:
>>>kFFT <<<
Parsing failed due to invalid input!
Stopping on parser failure
cannot compile orchestra
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
1 errors in performance
no sound written to disk
```

**Comment by Oeyvind** [comment]
Ok. It seems the Linux binary packages are a little bit behind the most
current version. This is probably because it is relatively easy to build
from source on Linux.
Instructions here:
https://github.com/csound/csound/blob/develop/BUILD.md

Could you try updating Csound and try again?
The error seems to be parser related, something that is not actually wrong,
but is interpreted as an error by the language parser.


2017-03-09 8:13 GMT-08:00 sensestage <notifications@github.com>:

**Comment by sensestage** [comment]
ok, then it works
